# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0:
    - firefox
    - google-chrome
    - chromium
  1:
    - spotify
    - strawberry
  2:
    - teamspeak
    - discord
  3:
    - deej.unmapped

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: /dev/ttyACM0
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default
